// <auto-generated />
using System;
using BulkInsertBug.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BulkInsertBug.Migrations
{
    [DbContext(typeof(BugnDbContext))]
    partial class BugnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("BulkInsertBug.Entities.Person_Bug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People_Bug");
                });

            modelBuilder.Entity("BulkInsertBug.Entities.Person_NoBug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People_NoBug");
                });

            modelBuilder.Entity("BulkInsertBug.Entities.Person_Bug", b =>
                {
                    b.OwnsOne("BulkInsertBug.Entities.BasicInfo", "BasicInfo", b1 =>
                        {
                            b1.Property<Guid>("Person_BugId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Person_BugId");

                            b1.ToTable("People_Bug");

                            b1.WithOwner()
                                .HasForeignKey("Person_BugId");

                            b1.OwnsOne("BulkInsertBug.Entities.Name", "Name", b2 =>
                                {
                                    b2.Property<Guid>("BasicInfoPerson_BugId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("First")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("FirstName");

                                    b2.Property<string>("Last")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("LastName");

                                    b2.HasKey("BasicInfoPerson_BugId");

                                    b2.ToTable("People_Bug");

                                    b2.WithOwner()
                                        .HasForeignKey("BasicInfoPerson_BugId");
                                });

                            b1.Navigation("Name");
                        });

                    b.Navigation("BasicInfo");
                });

            modelBuilder.Entity("BulkInsertBug.Entities.Person_NoBug", b =>
                {
                    b.OwnsOne("BulkInsertBug.Entities.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("Person_NoBugId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("First")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("FirstName");

                            b1.Property<string>("Last")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LastName");

                            b1.HasKey("Person_NoBugId");

                            b1.ToTable("People_NoBug");

                            b1.WithOwner()
                                .HasForeignKey("Person_NoBugId");
                        });

                    b.Navigation("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
